### ISSUE TITLE
Update shebang line to include env

### ISSUE THREAD

**Issue by adnan360** [Phate6660/bcalc#14]
I've [implemented bcalc](https://notabug.org/adnan360/openbox-config/src/master/src/local/share/openbox-config) into my config and it's working great for me. Recently I started to support FreeBSD as an alternate platform. Then I noticed something.

The current shebang line used in `bcalc` and `test` is:

```bash
#!/bin/bash
```

This is fine on GNU+Linux systems. But BSD systems such as FreeBSD and others store the bash binary in `/usr/local/bin/bash`, so it fails there saying `/bin/bash: bad interpreter: No such file or directory`. One way to fix this is to direct to bash through env, like this:

```bash
#!/usr/bin/env bash
```

Here is an [article](https://www.cyberciti.biz/tips/finding-bash-perl-python-portably-using-env.html) about why env should be included in shebang. There are discussions around the web whether this is needed. But general idea is that this is suggested if the script is intended to be portable. So I think this change should make it usable in more platforms.

**Comment by Phate6660** [comment]
Done. :)

**Comment by Phate6660** [comment]
Oh whoops forgot the test script, one sec.

**Comment by Phate6660** [comment]
And got it.

**Comment by adnan360** [comment]
It's working perfectly now. Thanks.

Also wanted to let you know I created a [rofi mode script](https://github.com/davatorium/rofi-scripts/tree/master/mode-scripts#calc) to make my runmenu.sh more modular. It suggests to use bcalc, which was recently [merged](https://github.com/davatorium/rofi-scripts/pull/26#event-4716220317) in the rofi-scripts community repo.
