### ISSUE TITLE
Include instructions on how to use it on README

### ISSUE THREAD

**Issue by adnan360** [Phate6660/bcalc#2]
It's up to you, but I think adding basic instructions on the README.md on how to use it would be nice. Plus some examples, some limitations (e.g. #1) in the readme would make it more user friendly and show what it's capable of before downloading it.

**Comment by Phate6660** [comment]
I updated the README. Let me know what you think.

**Comment by adnan360** [comment]
Thanks. Looks much better.

**Comment by Phate6660** [comment]
@adnan360 Just wanted to ping you and let you know that I believe I've managed to implement PEMDAS support. Would you be open to testing it a little bit?
